version: '3.4'

services:
  database:
    image: postgres:10.5
    container_name: database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=reksoft

  builder:
    build:
      context: ./database
      dockerfile: dockerfile
    image: builder
    container_name: builder
    depends_on:
      - database

  application:
    build:
      context: .
      dockerfile: dockerfile
    image: application
    container_name: application
    ports:
      - 80:8080
    depends_on:
      - builder